name: Create Github release

on:
  push:
    tags:
      - "v*.*.*" # triggers on tags like vX.Y.Z

jobs:

  run-only-on-main-branch:
    name: Verify main branch
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if tag is on main
        run: |
          git fetch origin main
          if git merge-base --is-ancestor $GITHUB_SHA origin/main; then
            echo "Tag is on main"
          else
            echo "Tag is NOT on main, skipping"
            #exit 1
          fi

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
	needs: run-only-on-main-branch
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract changelog for current version
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME#v}"  # Remove leading "v" (e.g. vX.Y.Z → X.Y.Z)
          echo "Extracting changelog for version $TAG"

          # Extract section for this version up to the next version header
          awk "/## \\[$TAG\\]/,/^---/" CHANGELOG.md > release_notes.tmp

          # Clean up formatting (remove trailing ---)
          sed -i '/^---/d' release_notes.tmp

          # Verify
          echo "==== Extracted release notes ===="
          cat release_notes.tmp
          echo "================================"

          echo "body_path=release_notes.tmp" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090
        with:
          name: "JInputGuard ${{ github.ref_name }}"
          body_path: ${{ steps.changelog.outputs.body_path }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
