name: Publish Core Module to Maven Central

on:
  push:
    tags:
      - 'v*'  # Runs only for version tags (e.g., v1.0.0)
    branches:
      - release/*


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract version from Git tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update pom.xml version
        run: |
          mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}
          git commit -am "Set version to ${{ env.RELEASE_VERSION }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: mvn clean test

      - name: Build and package
        run: mvn clean install

      - name: Publish RELEASE to Maven Central
        run: |
          mvn -P release --batch-mode deploy -am -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Push version change
        run: |
          git push origin HEAD

      - name: Bump to next SNAPSHOT version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          NEXT_VERSION=$(echo ${{ env.RELEASE_VERSION }} | awk -F. '{print $1"."$2"."$3+1"-SNAPSHOT"}')
          mvn versions:set -DnewVersion=$NEXT_VERSION -am
          git commit -am "Set version to $NEXT_VERSION"
          git push origin HEAD
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish Git Flow Release
        run: |
          RELEASE_BRANCH=$(git branch --show-current)
          git checkout main
          git merge --no-ff $RELEASE_BRANCH -m "Merge release ${{ env.RELEASE_VERSION }} into main"
          git push origin main

          git checkout develop
          git merge --no-ff $RELEASE_BRANCH -m "Merge release ${{ env.RELEASE_VERSION }} into develop"
          git push origin develop

          git push origin --delete $RELEASE_BRANCH || echo "Branch already deleted or not pushed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}